import { Tank } from './Tank';

export const TANKS: Tank[] = [
  {
    id: 1,

    nombre: 'Tanque 1',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 2,

    nombre: 'Tanque 2',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 3,

    nombre: 'Tanque 3',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 4,

    nombre: 'Tanque 4',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 5,

    nombre: 'Tanque 5',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 6,

    nombre: 'Tanque 6',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 7,

    nombre: 'Tanque 7',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 8,
    nombre: 'Tanque 8',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },

  {
    id: 9,
    nombre: 'Tanque 9',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 10,
    nombre: 'Tanque 10',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 11,
    nombre: 'Tanque 11',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 12,
    nombre: 'Tanque 12',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 13,
    nombre: 'Tanque 13',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 14,
    nombre: 'Tanque 14',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
  {
    id: 15,
    nombre: 'Tanque 15',
    matDescrption: 'Agua',
    batchNo: '1',
    client: 'Tesla',
    startDate: '04-03-2021',
    deliveryDate: '07-03-2021',
    etapaActual: 'Cargando',
    status: 'green',
  },
];
